# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Bergrübe
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure CouchDB paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ couchdb_uid }}"
    group: "{{ couchdb_gid }}"
  with_items:
    - "{{ couchdb_base_path }}"
    - "{{ couchdb_config_path }}"
    - "{{ couchdb_data_path }}"

- name: Ensure CouchDB support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ couchdb_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ couchdb_uid }}"
    group: "{{ couchdb_gid }}"
  with_items:
    - env
    - labels
  register: couchdb_support_files_result

- name: Ensure CouchDB configuration file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ couchdb_config_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ couchdb_uid }}"
    group: "{{ couchdb_gid }}"
  with_items:
    - local.ini
  register: couchdb_config_file_result

- name: Ensure CouchDB container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ couchdb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ couchdb_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else couchdb_container_image_force_pull }}"
  register: couchdb_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: couchdb_container_image_pull_result_ansible_module is not failed

- name: Ensure CouchDB container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ couchdb_container_image }}"
  register: couchdb_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: couchdb_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in couchdb_container_image_pull_result_command.stdout"

- name: Ensure CouchDB container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ couchdb_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: couchdb_network_creation_result

- name: Ensure CouchDB container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ couchdb_container_network }}
  register: couchdb_network_creation_result
  changed_when: couchdb_network_creation_result.rc == 0
  failed_when: couchdb_network_creation_result.rc != 0 and 'already exists' not in couchdb_network_creation_result.stderr

- name: Ensure CouchDB systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/couchdb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ couchdb_identifier }}.service"
    mode: "0644"
  register: couchdb_systemd_service_result

- name: Determine whether CouchDB needs a restart
  ansible.builtin.set_fact:
    couchdb_restart_necessary: >-
      {{
        couchdb_support_files_result.changed | default(false)
        or couchdb_config_file_result.changed | default(false)
        or couchdb_systemd_service_result.changed | default(false)
        or couchdb_container_image_pull_result_ansible_module.changed | default(false)
        or couchdb_container_image_pull_result_command.changed | default(false)
        or couchdb_container_image_build_result.changed | default(false)
      }}
